# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);

insert into "people" values(1, 'Bob', 23);
insert into "people" values(2, 'Rob', 21);

# --- !Downs

drop table "people" if exists;
